# Generated by Django 5.0.6 on 2024-12-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='type',
            field=models.CharField(choices=[('SDFEAM', 'situation deploiment du FORISIEM et etat des alertes majeurs'), ('ACIBCM', "alertes critique de l'infrastructure BCM"), ('EAVEE', 'etat anti verus et EDR ESET ')], default='type1', max_length=10),
        ),
    ]
