# Generated by Django 5.0.6 on 2024-12-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmApp', '0002_alter_files_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('situation deploiment du FORISIEM et etat des alertes majeurs', 'situation deploiment du FORISIEM et etat des alertes majeurs'), ("alertes critique de l'infrastructure BCM", "alertes critique de l'infrastructure BCM"), ('etat anti verus et EDR ESET', 'etat anti verus et EDR ESET ')], default='situation deploiment du FORISIEM et etat des alertes majeurs', max_length=255)),
                ('actions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='bcmApp.action')),
            ],
        ),
        migrations.AlterField(
            model_name='files',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='bcmApp.type'),
        ),
    ]
